### ISSUE TITLE
Indigo services to support ketcher

### ISSUE THREAD

**Issue by cmgrulke** [Chemical-Curation/chemcurator_vuejs#20]
**As a** user
**I want** services deployed to support ketcher
**So that** I can paste in SMILES to Ketcher and do 2D cleaning of structures

**Acceptance Criteria:**
Ketcher will allow me to paste SMILES and return the structure depiction and perform 2D cleaning of structures. 

**Test(s):**

**Comment by mcovalt** [comment]
This was implemented in a Dockerfile posted in the [wiki](https://github.com/Chemical-Curation/chemcurator_vuejs/wiki/Ketcher). The Dockerfile is intended to replace the [`chemicalcuration/ketcher`](https://hub.docker.com/r/chemicalcuration/ketcher) image as it serves both the static content of Ketcher and the Indigo Services app.

It is important to note a few things on that image:

- It is based off of the [`epmlsop/indigo_service`](https://hub.docker.com/r/epmlsop/indigo_service) image. This image uses `supervisord` to manage a few of services inside a single Docker container (Redis, Celery, and uWSGI). This is typically considered an anti-pattern as each Docker container is supposed to do one-and-only-one thing.
- A webserver is required to set CORS headers for the API. Nginx was installed into the [`epmlsop/indigo_service`](https://hub.docker.com/r/epmlsop/indigo_service) image to accomplish this.
- Since we have a webserver running in that image, we might as well add the Ketcher static files! It is built in the container and served along side the Indigo Services API.
- The CORS header is set to the wildcard `*`, which may not be a great idea. We can set this to a specific domain down-the-road. But for now, this alleviates some complexity.

**Comment by mwfrost** [comment]
There is no PR for this ticket - it involves changes to the ketcher image at `https://hub.docker.com/r/chemicalcuration/ketcher`. I tested it by building the container and identifying a chemical image in the Ketcher window.
